curate:
  fields:
    dry_run:
      required: false
      default: false
      selector:
        boolean:

curate_ids:
  fields:
    device_id:
      required: false
      selector:
        device:
          multiple: true
    previous_name:
      required: false
      selector:
        text:
    dry_run:
      required: false
      default: true
      selector:
        boolean:
